### ISSUE TITLE
Refused to apply style from <URL> because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled

### ISSUE THREAD

**Issue by muneebbug** [uicrooks/shopify-theme-lab#107]
![image](https://user-images.githubusercontent.com/72074109/126800325-10a16811-1b59-4308-8bf2-c0025779b51a.png)

**Comment by sergejcodes** [comment]
The issue is not reproducible with the base version. Please create a new bug report and provide more detailed information. 

But since your screenshot indicates you are in development mode the bundle.css won't be loaded anyways see [limitations](https://themelab.uicrooks.com/guide/troubleshooting.html#limitations)
