### ISSUE TITLE
[Bug]: Adding images

### ISSUE THREAD

**Issue by ineptian** [uicrooks/shopify-theme-lab#117]
### Operating system

Windows 10

### Node.js version

15.5.0

### Shopify CLI version

2.1.0

### Browsers

Chrome

### Version

4 (Current)

### Details

1. Add image.static.jpg to assets folder.
2. Reference {{ 'image.static.jpg' | asset_url }}
3. Get error 422 in chrome console. On shopify asset url the error is "Transformation Failed"

Attached screenshot of error in chrome console as well as asset url on shopify side.

![image](https://user-images.githubusercontent.com/7462616/127752578-8838e70f-169b-4e01-a5f0-85e798017858.png)
![image](https://user-images.githubusercontent.com/7462616/127752585-23ec5681-25c3-4e6e-8c34-d2062f776240.png)

### Notice

- [X] I read the notice

**Comment by sergejcodes** [comment]
This is a Shopify CLI bug. Currently, all binary file uploads are broken (images, fonts etc). Here's a [comment from me on a similar issue in the Shopify CLI Repo](https://github.com/Shopify/shopify-cli/issues/1401#issuecomment-891127561)

**Comment by sergejcodes** [comment]
This is too risky if you use a Shopify CLI command which pushes all files back to remote then all files will be broken again.

1. I would place all files like you normally would in the assets directory and don't use them until the Shopify CLI issue is resolved
2. Additionally upload these assets to the Shopify Files and use the provided cdn URLs  `<img src="https://cdn.shopify.com/...">` instead of e.g. `{{ 'image.static.jpg' | asset_url }}` for now

![screen](https://user-images.githubusercontent.com/68379148/127924660-268108c5-1c47-4c7d-a383-14ce1d75ea34.png)

**Comment by ineptian** [comment]
Looks like there is a fix for this finally, just waiting for it to get pulled into the main branch.

https://github.com/Shopify/shopify-cli/pull/1457

**Comment by sergejcodes** [comment]
This issue should now be fixed with the latest Shopify CLI [2.3.0](https://github.com/Shopify/shopify-cli/blob/main/CHANGELOG.md#version-230) release.
