### ISSUE TITLE
Captcha white screen of death?

### ISSUE THREAD

**Issue by artless01** [uicrooks/shopify-theme-lab#157]
### Operating system

MacOS 10.15.7

### Node.js version

12.13.0

### Shopify CLI version

2.7.1

### Browsers

Chrome

### Version

4 (Current)

### Details

I'm having a problem rendering `{{ content_for_layout }}` on the recaptcha template using the if statement block included in `theme.liquid`. Since the if statement ensures Vue instance isn't initialized, I wouldn't imagine it'd be a Vue issue. The `template-captcha.liquid` snippet is rendering, but `{{ content_for_layout }}` isn't loading anything. Ever seen this before? Any ideas as to why this might be occurring? Thanks in advance.

Love Theme Lab and Foundation theme btw!

### Notice

- [X] I read the notice

**Comment by artless01** [comment]
![Screen Shot 2022-03-18 at 12 52 09 PM](https://user-images.githubusercontent.com/16629379/159048198-cda88903-5bab-4bab-bbc6-c2bd29511a83.png)
![Screen Shot 2022-03-18 at 12 48 57 PM](https://user-images.githubusercontent.com/16629379/159048306-8fce3642-c523-4bb3-b689-00ae6ac6b264.png)
![Screen Shot 2022-03-18 at 12 52 13 PM](https://user-images.githubusercontent.com/16629379/159048412-a7a0e6c4-8534-435c-bb0c-d9324dff5bdd.png)

**Comment by youngbloodk** [comment]
Having the same issue on all browsers. Just a white screen.

**Comment by DEV-ONI** [comment]
The `content_for_layout` is not being rendered properly from within the snippet. 
Upon inspecting the page you will notice it is completely empty.

Just reference it directly on `theme.liquid` and that should work.

I'm using an AlpineJS  fork of this template and had the same problem - but it seems to be related to Shopify and not due to this particular Vue implementation.
