### ISSUE TITLE
Add https://eslint.vuejs.org/rules/ to .eslintrc.js

### ISSUE THREAD

**Issue by james0r** [uicrooks/shopify-theme-lab#55]
Was a bit verbose for me out of the box figuring that the VSCode Vetur formatting doesn't clean most of this stuff up.

Might be helpful to have this link in there, took me a few minutes to find it.

**Comment by sergejcodes** [comment]
Hi 👋,

can you elaborate a bit. Are you using the Vetur extension to automatically fix any fixable errors inside your Vue files? Or are you using the lint task inside `package.json` and are adding the `--fix` flag? 

Since not everyone is going to use Vetur it might be better to add a notice and link to the ESLint docs inside `.eslintrc.js`. Would something like this be helpful?

```js
/*
 * by running 'npm run lint:js -- --fix' in the command line ESLint can automatically fix some of the reported problems
 * see https://eslint.org/docs/rules for more details
 */

...
```

**Comment by james0r** [comment]
Ya I'm using Vetur but I'm more talking about the console output.

Just kinda flooded with linting warnings out the box when not following the formatting rules. 

I was tipped off by the existing comment regarding eslint rules and then googled my way to the Vue specific rules which I ended up using to reduce the linting warnings by going with vue/essential.

**Comment by sergejcodes** [comment]
The latest [v2.4.14](https://github.com/uicrooks/shopify-theme-lab/releases/tag/v2.4.14) release now implements this notice in `.eslintrc.js` 95e249a94eb4881209e2f91e33a1b2992ca5afd5
